CREATE TABLE Manufacturer (
    [mfgID] INT IDENTITY(1,1) PRIMARY KEY,
    [mfg] VARCHAR(85),
    [dateCreated] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [dateUpdated] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [dateArchived] DATETIME,
    [createdBy] INT NOT NULL DEFAULT((0)),
    [updateBy] INT NOT NULL DEFAULT((0)),
    [archivedBy] INT
);
INSERT INTO Manufacturer VALUES
    ('4Kids Entertainment'),
    ('5Finity'),
    ('Ace Authentic'),
    ('Action Packed'),
    ('AEG'),
    ('AEG/Phoenix Interactive'),
    ('Alchemia'),
    ('Alchemist Empire'),
    ('Alderac Entertainment Group'),
    ('Allworld'),
    ('Amada Printing'),
    ('Amada Printing/Clamp'),
    ('Ankama Games/Upper Deck'),
    ('Arcane Tinmen'),
    ('Artbox Entertainment'),
    ('Atlas Games'),
    ('Automoton'),
    ('Bandai'),
    ('Bandai/Amada Printing'),
    ('BBC Worldwide'),
    ('Beast Clans LLC'),
    ('Beholder Kft.'),
    ('Best'),
    ('Bible Battles Trading Card Game, LLC'),
    ('Black Dragon Press'),
    ('Blue Ocean Entertainment/Burda Publishing Polska'),
    ('Bowman Gum'),
    ('Brady Games'),
    ('Bro! Novelties'),
    ('Broccoli'),
    ('Broccoli / Nippon Ichi Software'),
    ('Bushiroad, Ltd.'),
    ('Cactus Game Design'),
    ('Cahaba Productions Inc.'),
    ('Caliber Games Systems'),
    ('Card Sharks, Inc.'),
    ('CARDZ'),
    ('Cartamundi'),
    ('CCP Games'),
    ('Cell Entertainment AB'),
    ('Chaosium'),
    ('Chessex'),
    ('Classic Games, Inc.'),
    ('Collect-A-Card'),
    ('Collector''s Edge'),
    ('Columbia Games'),
    ('Comic Images'),
    ('Comic Images/Tempo Games'),
    ('Comic Images/WWE'),
    ('Companion Games'),
    ('Courtside'),
    ('Creek'),
    ('Cryptozoic'),
    ('Cryptozoic Entertainment'),
    ('Cult Stuff'),
    ('Daedelus Entertainment/Z-Man Games, Inc./Loch Ness Games, Inc./Inner Kingdom Games'),
    ('Dart Flipcards'),
    ('Decipher'),
    ('Decipher, Inc.'),
    ('Destini Productions Inc.'),
    ('Digimon'),
    ('Dino Entertainment/Panini'),
    ('Disney'),
    ('Diving Dragon Games'),
    ('Domo Sur SRL'),
    ('Donruss'),
    ('Dragstarr Games'),
    ('Draim'),
    ('Egmont Polksa'),
    ('Enix/Tenky'),
    ('Ensky/Movic'),
    ('Enterbrain'),
    ('Enterplay'),
    ('Entropic Games'),
    ('Epoch'),
    ('Existence Games'),
    ('Extreme Sports'),
    ('Ezekiel Limited'),
    ('F.X. Schmid/Gibsons Games'),
    ('Fanpro/Between the Stars'),
    ('Fantasy Flight Games'),
    ('Fantasy World, Inc./Hobby World'),
    ('Fantom'),
    ('FASA/WizKids'),
    ('Fishtank'),
    ('Five Rings Publishing Group/Wizards of the Coast/AEG'),
    ('Fleer'),
    ('Fleer/SkyBox International'),
    ('Force of Will Ltd.'),
    ('FPG, Inc.'),
    ('Front Row'),
    ('Futera'),
    ('Game On Sports, Inc.'),
    ('GameQuarters'),
    ('Games Lab'),
    ('Gandharvas Studio'),
    ('GE Fabbri'),
    ('Genuine Article'),
    ('Gernilex Bt.'),
    ('Giochi Preziosi'),
    ('Goodwin & Company'),
    ('Goudey'),
    ('Grand Slam Ventures'),
    ('Grandstand'),
    ('Gree'),
    ('Group SNE'),
    ('Harper Prism/Clive Barker'),
    ('Hero Factory'),
    ('Hi-Tech'),
    ('Hidden City'),
    ('Hidden City Games/Conceptcard'),
    ('Hobby Japan/Last Level/Square Enix/Neo Productions Unlimited'),
    ('Hoguma Entertainment'),
    ('IguanaBee'),
    ('Ikon Games'),
    ('Illektron'),
    ('ImagiNation Sports, LLC.'),
    ('Insight Games'),
    ('Interactive Imagination'),
    ('Iron Crown Enterprises'),
    ('Jasco Games'),
    ('JOGO Inc'),
    ('Journeyman Press'),
    ('Journeyman Press/The United States Playing Card Company'),
    ('Just Minors'),
    ('Kadokawa'),
    ('Kayo'),
    ('Kenzer & Company'),
    ('Koei Co. Ltd.'),
    ('Konami'),
    ('Krakowska Grupa Kreatywna'),
    ('Kris Silver'),
    ('Last Unicorn Games'),
    ('Last Unicorn Games/Five Rings Publishing Group/Wizards of the Coast'),
    ('Leaf fight TCG'),
    ('Leaf, Inc.'),
    ('Legend Story Studios'),
    ('Lethal Entertainment, Inc.'),
    ('Lucid Raven Productions'),
    ('M.M.G. Ltd.'),
    ('Mag Force 7'),
    ('Marvel Enterprises, Inc.'),
    ('Mattel'),
    ('Matter Group'),
    ('Maxx'),
    ('Mayfair Games'),
    ('Medallion Simulations'),
    ('media Factory'),
    ('Media Works'),
    ('Mega House'),
    ('Moments in History'),
    ('Monsterwax'),
    ('Movic'),
    ('Multi-Ad'),
    ('MultiSim'),
    ('MythIntentions, LLC'),
    (' Communications'),
    ('Naipes Heraclio Fournier'),
    ('National Chicle'),
    ('NCS'),
    ('NECA'),
    ('Neo Productions Unlimited'),
    ('NetPro'),
    ('New Media Publishing'),
    ('New Millennium Entertainment'),
    ('Nintendo'),
    ('Nintendo/Intelligent Systems'),
    ('Northeast Games, Inc.'),
    ('O-Pee-Chee'),
    ('Pacific Trading Cards'),
    ('Panini'),
    ('Panini Games'),
    ('Panini Group'),
    ('Parkhurst Products'),
    ('Pentakl Publishing'),
    ('Pinnacle Brands'),
    ('Pinnacle Entertainment Group'),
    ('Pioneer Entertainment/Pioneer Animation'),
    ('PKXL Cards, Inc.'),
    ('PlayFusion Limited/Games Workshop'),
    ('PlayFusion Ltd'),
    ('Playoff Inc'),
    ('Portal Games Ltd.'),
    ('Precedence Entertainment'),
    ('Precedence Entertainment/HarperCollins/HarperPrism/Zehrapushu/ZI Games'),
    ('Precedence Entertainment/Palladium Books'),
    ('Precedence Entertainment/Tyranny Games/Zehrapushu/ZI Games'),
    ('Press Pass, Inc.'),
    ('Pro Set'),
    ('ProCards'),
    ('Quality Playing'),
    ('Quantuum Magic'),
    ('Rainbow Games/Upper Deck'),
    ('Rapid POD Printing'),
    ('Rapidpod'),
    ('Rawen Group Hungary'),
    ('Razor Entertainment'),
    ('RC2 Inc./JoyRide Studios'),
    ('RCS MediaGroup'),
    ('Rittenhouse'),
    ('Romancing Cathay'),
    ('Round Table Productions'),
    ('Royal Rookies'),
    ('Ryvah'),
    ('SA-GE Collectibles, Inc.'),
    ('Sabertooth Games'),
    ('SALO'),
    ('Salo S.A'),
    ('SC Patiart SRL'),
    ('SCE Japan'),
    ('Schmidt Spiele'),
    ('Score'),
    ('Score Entertainment'),
    ('Showmans'),
    ('Signature Rookies'),
    ('SilverBlitz'),
    ('Sir Mantraplay'),
    ('SK Japan'),
    ('SkyBox'),
    ('SkyBox International/Fleer'),
    ('Slag-Blah Entertainment/Studio Foglio'),
    ('Social Games/ImageNative Worlds, Inc./R. Talsorian Games, Inc.'),
    ('Sony'),
    ('Spin Master'),
    ('SRG Universe Inc.'),
    ('Stampii'),
    ('Star Co.'),
    ('Star Pics'),
    ('Steve Jackson Games'),
    ('Stone Ring Games/Horizon Games'),
    ('Strategy Entertainment'),
    ('Super Heat Games'),
    ('Superior Pix'),
    ('Superior Rookies'),
    ('Takara'),
    ('Target Games'),
    ('Target Games/Heartbreaker Hobbies'),
    ('Tea Ice Tokyo'),
    ('Tecmo'),
    ('Terranetz'),
    ('Third World Games'),
    ('Thunder Castle Games'),
    ('Toggo'),
    ('Tomy'),
    ('Topps'),
    ('Traks'),
    ('Trio Toys'),
    ('TRISTAR'),
    ('Trok TCG'),
    ('TSR');
INSERT INTO Manufacturer VALUES
    ('U.S. Games Systems'),
    ('Ultimate Games'),
    ('Upper Deck'),
    ('Upper Deck/Cryptozoic Entertainment'),
    ('USA Baseball'),
    ('Valhalla Páholy Kft/CCG Art Kft/Két Mágus Kft/Delta Vision Kft'),
    ('Vandaria'),
    ('Voyager Promotions'),
    ('Warmoves Inc.'),
    ('Wax Eye'),
    ('Webkinz'),
    ('White Wolf Publishing'),
    ('Wild Card'),
    ('WildStorm Productions'),
    ('Wizards of the Coast'),
    ('Wizards of the Coast/Nintendo'),
    ('Wizards of the Coast/Takara'),
    ('Wizards of the Coast/White Wolf Publishing, Inc.'),
    ('Wizards of the Coast/White Wolf Publishing, Inc./PDA/Black Chantry'),
    ('WizKids'),
    ('Wolf Fang P.H.'),
    ('Wonder Bread'),
    ('Wydawnictwo Imperium'),
    ('Wydawnictwo Wieszcze');