CREATE TABLE Item (
    [itemID] INT IDENTITY(1,1) PRIMARY KEY,
    [indivID] INT FOREIGN KEY REFERENCES Individual(indivID),
    [typeID] INT FOREIGN KEY REFERENCES [Type](typeID),
    [subtypeID] INT FOREIGN KEY REFERENCES Subtype(subtypeID),
    [mfgID] INT FOREIGN KEY REFERENCES Manufacturer(mfgID),
    [brandID] INT FOREIGN KEY REFERENCES Brand(brandID),
    [setTypeID] INT FOREIGN KEY REFERENCES SetType(setTypeID),
    [teamID] INT FOREIGN KEY REFERENCES Team(teamID),
    [graded] BIT DEFAULT((0)),
    [condGradeID] INT FOREIGN KEY REFERENCES CondiationGrade(condGradeID),
    [valMin] NUMERIC(8,2),
    [valMax] NUMERIC(8,2),
    [imgFront] IMAGE,
    [imgBack] IMAGE,
    [imgOther] IMAGE,
    [notes] CHAR,
    [dateCreated] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [dateUpdated] DATETIME DEFAULT CURRENT_TIMESTAMP,
    [dateArchived] DATETIME,
    [createdBy] INT NOT NULL DEFAULT((0)),
    [updateBy] INT NOT NULL DEFAULT((0)),
    [archivedBy] INT,
);